added something that should've been added 2 weeks ago

diff --git a/fsa b/fsa
--- a/fsa
+++ b/fsa
@@ -1,12 +1,3 @@
-cd ./sshrd || { echo "Did you just double-clicked the executable? Plz cd into your 'FuckSetupApp' directory and run './fsa' manually. DON'T BE LAZY!"; exit 1; }
-OS=$(uname -s)
-case "$OS" in
-    Darwin) BIN_DIR="./Darwin" ;;
-    Linux)  BIN_DIR="./Linux" ;;
-    *)      echo "i said no windows dud, are you using Git Bash?"; exit 1 ;;
-esac
-
-killall iproxy 2>/dev/null | true
 echo " ____  _   _  ____  _   _  _____ ____  _____  _   _  _____    _    ____   ____"
 echo "|  __|| | | |/  __|| | / //  __/| ___||__ __|| | | |/  _  \  / \  /  _ \ /  _ \ " 
 echo "| |__ | | | || /   | |/ / | |__ | |__   | |  | | | || |_| | / . \ | |_| || |_| |"
@@ -24,12 +15,34 @@ echo "PLEASE THINK TWICE BEFORE PROCEEDING. YOU CAN ALSO PRESS CTRL + C TO EXIT.
 echo "You can learn how to use SSHRD_Script to extract the files in your device"
 echo "--------------------------------------------------------------------------------"
 echo "This script only supports 6.0 - 12.4.4 and 13.0 - 13.2.3"
-echo "If you're not on that version, bye bye then"
+echo "And only device using A13 chip and below"
+echo "If you're not on that version or using devices with A13 above, it WON'T WORK"
+echo "Support for A12/A13 is in EARLY BETA, and Linux is NOT supported"
+echo "If you're using an A12/A13 device, please use it under parental supervision!"
 echo "--------------------------------------------------------------------------------"
-sleep 30
+sleep 3
 echo "Checking iOS Version..."
 sleep 5
-VERSION=$($BIN_DIR/ideviceinfo -k ProductVersion 2>&1)
+OS=$(uname -s)
+case "$OS" in
+    Darwin) BINDIR="./Darwin" ;;
+    Linux)  BINDIR="./Linux" ;;
+    *)      echo "i said no windows dud, are you using Git Bash?"; exit 1 ;;
+esac
+if [[ $OS == Darwin ]]; then
+    VERSION=$(./ideviceinfos/ideviceinfo_macos -k ProductVersion 2>&1)
+    MODEL=$(./ideviceinfos/ideviceinfo_macos -k ProductType 2>&1)
+elif [[ $OS == Linux ]]; then
+    VERSION=$(./ideviceinfos/ideviceinfo_linux -k ProductVersion 2>&1)
+    MODEL=$(./ideviceinfos/ideviceinfo_linux -k ProductType 2>&1)
+fi
+if [[ "$MODEL" == iPhone11* || "$MODEL" == iPhone12* ]]; then
+    RDDIR="./sshrd-u8"
+else
+    RDDIR="./sshrd"
+fi
+cd $RDDIR || { echo "Did you just double-clicked the executable? Plz cd into your 'FuckSetupApp' directory and run './fsa' manually. DON'T BE LAZY!"; exit 1; }
+killall iproxy 2>/dev/null | true
 if [[ -z "$VERSION" ]]; then
     echo "Where's the device?"
     exit 1
@@ -45,73 +58,109 @@ fi
 sleep 3
 echo "Now set your device to DFU mode."
 sleep 1
-echo "btw, are you using iPhone 7/8 or X?"
-echo "If you're using iPhone 7/8/X, type '2'."
-echo "If you're using any device besides these, (I mean All iPhones, iPads and iPod Touches using A11 and below), type '1'."
-read -p "Input number here: " wow
-if [[ $wow = 1 ]]; then 
+if [[ "$MODEL" == iPhone9* || "$MODEL" == iPhone10* || "$MODEL" == iPhone11* || "$MODEL" == iPhone12* ]]; then 
     echo "Make sure your device is in normal mode. If not, press Ctrl + C to exit"
     sleep 5
     echo "Entering recovery mode..."
-    export UCID=$($BIN_DIR/ideviceinfo -k UniqueDeviceID)
-    $BIN_DIR/ideviceenterrecovery $UCID
+    export UCID=$("$BINDIR"/ideviceinfo -k UniqueDeviceID)
+    "$BINDIR"/ideviceenterrecovery $UCID
+    RUCONNECTINGIT=$($BINDIR/irecovery -q)
+    if [[ $RUCONNECTINGIT == "*ERROR: Unable to connect to device*" ]]; then
+        echo "Where is your device?"
+        $BINDIR/irecovery -n
+        exit 1
+    else
+        boardcfgu8=$("$BINDIR"/irecovery -q | grep MODEL | sed 's/MODEL: //')
+        deviceidu8=$("$BINDIR"/irecovery -q | grep PRODUCT | sed 's/PRODUCT: //')
+        rdu8dir="$boardcfgu8-$deviceidu8"
+        sleep 3
+        echo "You need to press Volume Down button + power button for 4s,"
+        echo "Then release Volume Down button, hold home button for 10s"
+        echo "Press Enter when ready, the guide will start after pressing Enter"
+        read -s
+        echo "Get prepared..." 
+        echo "3" && sleep 1 && echo "2" && sleep 1 && echo "1" && sleep 1
+        echo "Press Power & Volume Down button" 
+        echo "4" && sleep 1 && echo "3" && sleep 1 && "$BINDIR"/irecovery -n && echo "2" && sleep 1 && echo "1" && sleep 1
+        echo "Release Power button, hold Volume Down button"
+        echo "8" && sleep 1 && echo "7" && sleep 1 && echo "6" && sleep 1 && echo "5" && sleep 1 && echo "4" && sleep 1 && echo "3" && sleep 1 && echo "2" && sleep 1 && echo "1" && sleep 1
+    fi
+else
+    echo "Make sure your device is in normal mode. If not, press Ctrl + C to exit"
+    sleep 5
+    echo "Entering recovery mode..."
+    export UCID=$("$BINDIR"/ideviceinfo -k UniqueDeviceID) 
+    "$BINDIR"/ideviceenterrecovery $UCID 
     sleep 3
-    echo "You need to press home button + power button for 4s,"
-    echo "Then release power button, hold home button for 10s"
+    echo "You need to press Home button + power button for 4s,"
+    echo "Then release power button, hold Home button for 10s"
     echo "Press Enter when ready, the guide will start after pressing Enter"
     read -s
     echo "Get prepared..." 
     echo "3" && sleep 1 && echo "2" && sleep 1 && echo "1" && sleep 1
     echo "Press Power & Home button" 
-    echo "4" && sleep 1 && echo "3" && sleep 1 && $BIN_DIR/irecovery -n && echo "2" && sleep 1 && echo "1" && sleep 1
-    echo "Release Power button, hold home button"
+    echo "4" && sleep 1 && echo "3" && sleep 1 && "$BINDIR"/irecovery -n && echo "2" && sleep 1 && echo "1" && sleep 1
+    echo "Release Power button, hold Home button"
     echo "8" && sleep 1 && echo "7" && sleep 1 && echo "6" && sleep 1 && echo "5" && sleep 1 && echo "4" && sleep 1 && echo "3" && sleep 1 && echo "2" && sleep 1 && echo "1" && sleep 1
-elif [[ $wow = 2 ]]; then
-    echo "Make sure your device is in normal mode. If not, press Ctrl + C to exit"
-    sleep 5
-    echo "Entering recovery mode..."
-    export UCID=$($BIN_DIR/ideviceinfo -k UniqueDeviceID) 
-    $BIN_DIR/ideviceenterrecovery $UCID 
-    sleep 3
-    echo "You need to press Volume Down button + power button for 4s,"
-    echo "Then release power button, hold Volume Down button for 10s"
-    echo "Press Enter when ready, the guide will start after pressing Enter"
-    read -s
-    echo "Get prepared..." 
-    echo "3" && sleep 1 && echo "2" && sleep 1 && echo "1" && sleep 1
-    echo "Press Power & Volume Down button" 
-    echo "4" && sleep 1 && echo "3" && sleep 1 && $BIN_DIR/irecovery -n && echo "2" && sleep 1 && echo "1" && sleep 1
-    echo "Release Power button, hold Volume Down button"
-    echo "8" && sleep 1 && echo "7" && sleep 1 && echo "6" && sleep 1 && echo "5" && sleep 1 && echo "4" && sleep 1 && echo "3" && sleep 1 && echo "2" && sleep 1 && echo "1" && sleep 1
-else
-    echo "I said 1 or 2 dude"
-    echo "And now we're starting this all over!"
-    sleep 2
-    exit 1
 fi
 echo "Now your device should be in DFU mode...hopefully."
 echo "If not, Press Ctrl + C restart the script and do it again. sry"
-read -s 
+sleep 3
 echo "THIS SCRIPT WILL ERASE ALL DATA ON THIS DEVICE, AND IT WLL NEVER BE RECOVERED!"
 echo "Press Enter to proceed."
-echo "Please wait for ramdisk to be extracted..."
-echo "If the script got stuck, try press Enter for 1 time"
-echo "This could happen when you run this script for the second time"
-./sshrd.sh "$VERSION"
-if [[ $? -ne 0 ]]; then
-    echo "ou shii extract failed"
-    exit 1
+read -s
+if [[ "$MODEL" == iPhone11* || "$MODEL" == iPhone12* ]]; then
+    echo "Now plug your device in your Pi Pico/Waveshare board to enter pwned DFU mode"
+    echo "You can check the status of that LED light on your board to make sure it's successfully pwned."
+    echo "More detailed informations is mentioned in https://github.com/prdgmshift/usbliter8"
+    while true; do
+        echo "After pwning, press Enter"
+        read -s
+        echo "Checking DFU status..."
+        sleep 3
+        PWNA12=$("$BINDIR"/irecovery -q | grep PWND)
+        if [[ $PWNA12 == *usbliter8* ]]; then
+            echo "Your device is successfully pwned!"
+            break 
+        else
+            echo "Pwning failed. Please restart."
+            sleep 2
+        fi
+    done
+    echo "Please wait for ramdisk to be extracted..."
+    ./makebootfiles.sh "$VERSION" ./sshrd-u8/firmwares.json
+    if [[ $? -ne 0 ]]; then
+        echo "ou shii extract failed"
+        exit 1
+    fi
+    echo "Extraction completed!...hopefully. Now booting ramdisk..."
+    sleep 3
+    ./spiro.sh boot "$rdu8dir"
+    if [[ $? -ne 0 ]]; then
+        echo "ou shii boot failed"
+        exit 1
+    fi
+    echo "Now connecting to SSH..."
+else
+    echo "Please wait for ramdisk to be extracted..."
+    echo "If the script got stuck, try press Enter for 1 time"
+    echo "This could happen when you run this script for the second time"
+    ./sshrd.sh "$VERSION"
+    if [[ $? -ne 0 ]]; then
+        echo "ou shii extract failed"
+        exit 1
+    fi
+    echo "Extraction completed!...hopefully. Now booting ramdisk..."
+    echo "If the script got stuck, try press Enter for 1 time"
+    sleep 2
+    ./sshrd.sh boot
+    if [[ $? -ne 0 ]]; then
+        echo "ou shii boot failed"
+        exit 1
+    fi
+    echo "Stuck again? Press Enter 1 time"
+    sleep 20
 fi
-echo "Extraction completed! Booting ramdisk..."
-echo "If the script got stuck, try press Enter for 1 time"
-sleep 2
-./sshrd.sh boot
-if [[ $? -ne 0 ]]; then
-    echo "ou shii boot failed"
-    exit 1
-fi
-echo "Stuck again? Press Enter 1 time"
-sleep 20
 
 ver_ge() {
     local sorted
@@ -175,7 +224,7 @@ else
 fi
 
 killall iproxy 2>/dev/null | true
-"$BIN_DIR/iproxy" 2222 22 >/dev/null 2>&1 &
+"$BINDIR/iproxy" 2222 22 >/dev/null 2>&1 &
 IPROXY_PID=$!
 
 for i in {1..10}; do
@@ -194,14 +243,13 @@ for i in {1..10}; do
         exit 1
     fi
 done
-killall $BIN_DIR/iproxy 2>/dev/null | true
-$BIN_DIR/iproxy 2222 22 &>/dev/null 2>&1 &
+
 sleep 3
-$BIN_DIR/sshpass -p 'alpine' ssh -T -o StrictHostKeyChecking=no -p2222 root@localhost << EOF
+"$BINDIR"/sshpass -p 'alpine' ssh -T -o HostKeyAlgorithms=+ssh-rsa StrictHostKeyChecking=no -p2222 root@localhost << EOF
     echo "About to perform Setup.app Elimination..."
     $REMOTE_SCRIPT
 EOF
 echo "Now your device should bypassed the activation lock...hopefully."
-echo "Remember, you can't sideload apps, log in iCloud
+echo "Remember, you can't sideload apps after bypassing, and there could be some problems with stock activation."
+echo "Please report in Issues in my repo if anything happens. Good luck!"
 kill $IPROXY_PID 2>/dev/null
-cd ..
